import { Nunito } from "next/font/google";
import "./globals.css";
import { Web5Provider } from "./web5Context";


const inter = Nunito({ subsets: ["vietnamese"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web5Provider>{children}</Web5Provider>
      </body>
    </html>
  );
}
